### ISSUE TITLE
Warning message when updating photo properties when 'Panorama' is not checked.

### ISSUE THREAD

**Issue by timinaust** [ThomasDaheim/piwigo-panorama#1]
Thanks for sharing this extension.

Warning:  [mysql error 1366] Incorrect integer value: '' for column `piwigo_db`.`piwigo_images`.`is_panorama` at row 1

I am getting this message at top of screen while updating photo properties in admin.php when is_panorama is not checked.  I have traced it to single_update call at line 59 in main.inc.php.  It looks like PHP is getting confused between boolean returned by isset and how it constructs the query in single_udpate. I am on php7.3 on debian.  Same issue occurs with quick edit at line 292.

The query logs as UPDATE `piwigo_images`   SET `is_panorama` = ''   WHERE `id` = '15724'

A quick workaround was... (line 57)

    single_update(
      IMAGES_TABLE,
      array('is_panorama' => ($row['is_panorama'])?1:0),
      array('id' => $_GET['image_id'])
      );

and (line 290)

    single_update(
      IMAGES_TABLE,
      array('is_panorama' => (isset($_POST['is_panorama'])?1:0)),
      array('id' => $page['image_id'])
      );

**Comment by ThomasDaheim** [comment]
What dialog exactly are you using? I was just playing around "Edit photo [Properties]" single-photo editing and I can't seem to reproduce the issue. Any special properties you are editing (nit sure how this could have any impact...)?

My setup:

    Piwigo 2.10.2 Check for upgrade
    Operating system: Linux
    PHP: 7.3.25 (Show info) [2020-12-04 20:21:36]
    MySQL: 5.5.60-0+deb7u1-log [2020-12-04 20:21:36]
    Graphics Library: External ImageMagick 6.9.10-23

Still, I think your modification makes sense to avoid any possible conversion issues. Will have a look at it.

**Comment by ThomasDaheim** [comment]
I have updated all three locations (there is also the section with mass-updates).
